const COINGECKO_IDS_BY_NAME: Record<string, string> = {
  "Bitcoin": "bitcoin",
  "Ethereum": "ethereum",
  "Tether": "tether",
  "BNB": "binancecoin",
  "Solana": "solana",
  "XRP": "ripple",
  "Cardano": "cardano",
  "Dogecoin": "dogecoin",
  "Tron": "tron",
  "Polkadot": "polkadot",
  "Chainlink": "chainlink",
  "Avalanche": "avalanche-2",
  "Shiba Inu": "shiba-inu",
  "Uniswap": "uniswap",
  "Near Protocol": "near",
  "Polygon": "polygon-ecosystem-token",
  "Litecoin": "litecoin",
  "Pepe": "pepe",
  "Aave": "aave",
  "Sui": "sui",
  "Aptos": "aptos",
  "Hedera": "hedera-hashgraph",
  "Monero": "monero",
  "Stellar": "stellar",
  "Cosmos": "cosmos",
  "Render": "render-token",
  "Bittensor": "bittensor",
  "Optimism": "optimism",
  "Arbitrum": "arbitrum",
  "Injective": "injective-protocol",
  "Kaspa": "kaspa",
  "Stacks": "stacks",
  "Filecoin": "filecoin",
  "Immutable": "immutable-x",
  "Fantom": "fantom",
  "Thorchain": "thorchain",
  "Sei": "sei-network",
  "Celestia": "celestia",
  "VeChain": "vechain",
  "Worldcoin": "worldcoin-wld",
  "Maker": "maker",
  "The Graph": "the-graph",
  "Algorand": "algorand",
  "Bonk": "bonk",
  "FLOKI": "floki",
  "Starknet": "starknet",
  "Ethena": "ethena",
  "Jupiter": "jupiter-exchange-solana",
  "Pyth Network": "pyth-network",
  "Oasis Network": "oasis-network",
  "Quant": "quant-network",
  "Theta": "theta-token",
  "Mina": "mina-protocol",
  "Tezos": "tezos",
  "Flow": "flow",
  "Chiliz": "chiliz",
  "Curve DAO": "curve-dao-token",
  "PancakeSwap": "pancakeswap-token",
  "Gala": "gala",
  "Sandbox": "the-sandbox",
  "Decentraland": "decentraland",
  "Axie Infinity": "axie-infinity",
  "EOS": "eos",
  "Neo": "neo",
  "Kava": "kava",
  "Zcash": "zcash",
  "IOTA": "iota",
  "Conflux": "conflux-token",
  "Synthetix": "synthetix-network-token",
  "Stepn": "stepn",
  "Helium": "helium",
  "JasmyCoin": "jasmycoin",
  "Notcoin": "notcoin",
  "dogwifhat": "dogwifcoin",
  "Popcat": "popcat",
  "Brett": "based-brett",
  "BOOK OF MEME": "book-of-meme",
  "Ether.fi": "ether-fi",
  "Pendle": "pendle",
  "Aevo": "aevo-exchange",
  "Wormhole": "wormhole",
  "LayerZero": "layerzero",
  "Blast": "blast",
  "Manta Network": "manta-network",
  "AltLayer": "altlayer",
  "Dymension": "dymension",
  "Ronin": "ronin",
  "Beam": "beam-2",
  "Illuvium": "illuvium",
  "Blur": "blur",
  "LooksRare": "looksrare",
  "Enjin Coin": "enjincoin",
  "Loopring": "loopring",
  "Compound": "compound-governance-token",
  "1inch Network": "1inch",
  "Basic Attention": "basic-attention-token",
  "Nexo": "nexo",
  "0x": "0x",
  "Ankr": "ankr",
  "Siacoin": "siacoin",
};

export function resolveCoinGeckoId(coin: {
  coinGeckoId?: string | null;
  name: string;
}): string | null {
  return coin.coinGeckoId ?? COINGECKO_IDS_BY_NAME[coin.name] ?? null;
}
